### ISSUE TITLE
Please delete

### ISSUE THREAD

**Issue by jennasalau** [JeromeFranco/missions-exercise#1]
Hi Jerome,

I have finished looking over your exercise.

Can you please delete this repo at your earliest connivence. I hope you can appreciate we do not want them public.

Thanks
Jenna

**Comment by jennasalau** [comment]
Hi Jerome.

Just a reminder to please delete this repo as it belongs to Deloitte.

If you do not take action we will be opening a DMCA takedown notice.

**Comment by JeromeFranco** [comment]
Alright. I'll delete this right away.
